# Generated by Django 2.1.5 on 2019-02-08 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('edition_year', models.PositiveSmallIntegerField(help_text='Format allowed: YYYY', validators=[django.core.validators.MaxValueValidator(2019)])),
            ],
        ),
    ]
